services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    env_file:
      - .env
    volumes:
      - ..:/workspaces:cached
      - app-node-modules:/workspaces/node_modules
      - app-command-history:${CONTAINER_HOME}/commandhistory
      - app-oh-my-zsh:${CONTAINER_HOME}/.oh-my-zsh
      - ~/.ssh:${CONTAINER_HOME}/.ssh:ro
      - ~/.gitconfig:${CONTAINER_HOME}/.gitconfig:ro

volumes:
  app-node-modules:
  app-command-history:
  app-oh-my-zsh:
